# Generated by Django 6.0.1 on 2026-01-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='URL of the product image', max_length=500, null=True),
        ),
    ]
